---
- hosts: local
  tasks:
    - name: Install FFMPEGS packages
      apt: name={{ item }} state=installed
      with_items:
        - libavcodec-dev
        - libavdevice-dev
        - libavfilter-dev
        - libavformat-dev
        - libavutil-dev
        - libpostproc-dev
        - libswscale-dev

    - name: Install CERES packages
      apt: name={{ item }} state=installed
      with_items:
        - libatlas-base-dev
        - libgflags-dev
        - libgoogle-glog-dev
        - libsuitesparse-dev

    - name: Install PYTHON packages
      apt: name={{ item }} state=installed
      with_items:
        - pep8
        - pyflakes
        - python-pip

    - name: Install DB packages
      apt: name={{ item }} state=installed
      with_items:
        - libmysqlclient-dev
        - mysql-common

    - name: Install OTHER packages
      apt: name={{ item }} state=installed
      with_items:
        - ant
        - autoconf
        - automake
        - build-essential
        - bzr
        - ccache
        - checkstyle
        - cmake
        - cmake-curses-gui
        - cppcheck
        - cppcheck
        - default-jdk
        - doxygen
        - emacs24
        - findbugs
        - freeglut3
        - freeglut3-dev
        - g++
        - g++-4.6
        - g++-4.8
        - gcc
        - gcc-4.6
        - gcc-4.8
        - git
        - git-core
        - git-gui
        - git-svn
        - gitk
        - glew-utils
        - gnome-session-flashback
        - gnome-tweak-tool
        - graphviz
        - htop
        - lcov
        - libavahi-client-dev
        - libavahi-compat-libdnssd-dev
        - libblas-dev
        - libblas3gf
        - libboost1.54-all-dev
        - libcppunit-dev
        - libeigen3-dev
        - libgl1-mesa-glx
        - libglew-dev
        - libglu1-mesa
        - libglu1-mesa-dev
        - liblapack-dev
        - libncurses5-dev
        - libpng12-dev
        - libprotobuf-c0
        - libprotobuf-c0-dev
        - libprotobuf-dev
        - libprotobuf-lite8
        - libprotobuf8
        - libprotoc-dev
        - libtbb-dev
        - libtbb2
        - libtool
        - libuuid1
        - libx11-dev
        - libxi-dev
        - libxmu-dev
        - libzmq3-dev
        - linux-headers-generic
        - linux-image-generic
        - linux-source
        - mercurial
        - meshlab
        - nvidia-profiler
        - nvidia-visual-profiler
        - openssh-client
        - openssh-server
        - protobuf-compiler
        - subversion
        - uuid-dev
        - valgrind
        - xvfb
