---
  - name: create SSH directory
    file: path=~/.ssh state=directory

  - name: generate SSH key
    user: name="{{ ansible_ssh_user }}" generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
