---
#ssh
  - name: create SSH directory
    file: path={{ ansible_env.HOME }}/.ssh state=directory

  - name: generate SSH key
    user: name="{{ ansible_ssh_user }}" generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa

  - name: Show SSH public key
    command: cat {{ ansible_env.HOME }}/.ssh/id_rsa.pub
    register: cat

  - debug: var=cat.stdout_lines

  - name: Copy SSH public key
    pause: prompt="Add the SSH key above to your BitBucket account. Press enter to continue..."
    register: pause

#packages
  - name: install packages
    sudo: true
    apt: name={{ item }} state=present
    with_items:
      - libavcodec-dev
      - libavdevice-dev
      - libavfilter-dev
      - libavformat-dev
      - libavutil-dev
      - libpostproc-dev
      - libswscale-dev
      - libatlas-base-dev
      - libgflags-dev
      - libgoogle-glog-dev
      - libsuitesparse-dev
      - pep8
      - pyflakes
      - python-pip
      - libmysqlclient-dev
      - mysql-common
      - ant
      - autoconf
      - automake
      - build-essential
      - bzr
      - ccache
      - checkstyle
      - cmake
      - cmake-curses-gui
      - cppcheck
      - cppcheck
      - default-jdk
      - doxygen
      - emacs24
      - findbugs
      - freeglut3
      - freeglut3-dev
      - g++
      - g++-4.6
      - g++-4.8
      - gcc
      - gcc-4.6
      - gcc-4.8
      - git
      - git-core
      - git-gui
      - git-svn
      - gitk
      - glew-utils
      - gnome-session-flashback
      - gnome-tweak-tool
      - graphviz
      - htop
      - lcov
      - libavahi-client-dev
      - libavahi-compat-libdnssd-dev
      - libblas-dev
      - libblas3gf
      - libboost1.54-all-dev
      - libcppunit-dev
      - libeigen3-dev
      - libgl1-mesa-glx
      - libglew-dev
      - libglu1-mesa
      - libglu1-mesa-dev
      - liblapack-dev
      - libncurses5-dev
      - libpng12-dev
      - libprotobuf-c0
      - libprotobuf-c0-dev
      - libprotobuf-dev
      - libprotobuf-lite8
      - libprotobuf8
      - libprotoc-dev
      - libtbb-dev
      - libtbb2
      - libtool
      - libuuid1
      - libx11-dev
      - libxi-dev
      - libxmu-dev
      - libzmq3-dev
      - linux-headers-generic
      - linux-image-generic
      - linux-source
      - mercurial
      - meshlab
      - nvidia-profiler
      - nvidia-visual-profiler
      - openssh-client
      - openssh-server
      - protobuf-compiler
      - subversion
      - uuid-dev
      - valgrind
      - xvfb

#repositories
  - name: clone meshify-superbuild
    git: repo=git@bitbucket.org:replicalabs/meshify-superbuild.git dest={{ ansible_env.HOME }}/meshify-superbuild accept_hostkey=yes

  - name: clone rendor-android-superbuild
    git: repo=git@bitbucket.org:replicalabs/rendor-android-superbuild.git dest={{ ansible_env.HOME }}/rendor-android-superbuild accept_hostkey=yes

  - name: clone ceres-solver
    git: repo=https://ceres-solver.googlesource.com/ceres-solver dest={{ ansible_env.HOME }}/ceres-solver

  - name: configure ceres-solver
    sudo: true
    command: cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS:BOOL=ON
    args:
      chdir: '{{ ansible_env.HOME }}/ceres-solver/'
      creates: '{{ ansible_env.HOME }}/ceres-solver/cmake_install.cmake'

  - name: build & install ceres-solver
    sudo: true
    command: sudo make -j4 install
    args:
      chdir: '{{ ansible_env.HOME }}/ceres-solver/'
      creates: '/usr/local/include/ceres/ceres.h'
