---
#This role contains computer vision stuff

#packages
  - name: install packages
    sudo: true
    apt: name={{ item }} state=present
    with_items:
      - libavcodec-dev
      - libavdevice-dev
      - libavfilter-dev
      - libavformat-dev
      - libavutil-dev
      - libpostproc-dev
      - libswscale-dev
      - libatlas-base-dev
      - libgflags-dev
      - libgoogle-glog-dev
      - libsuitesparse-dev
      - pep8
      - pyflakes
      - python-pip
      - libmysqlclient-dev
      - ant
      - autoconf
      - automake
      - build-essential
      - bzr
      - ccache
      - checkstyle
      - cmake
      - cmake-curses-gui
      - cppcheck
      - cppcheck
      - doxygen
      - freeglut3
      - freeglut3-dev
      - g++
      - g++-4.6
      - g++-4.8
      - gcc
      - gcc-4.6
      - gcc-4.8
      - glew-utils
      - graphviz
      - lcov
      - libavahi-client-dev
      - libavahi-compat-libdnssd-dev
      - libblas-dev
      - libblas3gf
      - libboost1.54-all-dev
      - libcppunit-dev
      - libeigen3-dev
      - libgl1-mesa-glx
      - libglew-dev
      - libglu1-mesa
      - libglu1-mesa-dev
      - liblapack-dev
      - libncurses5-dev
      - libpng12-dev
      - libprotobuf-c0
      - libprotobuf-c0-dev
      - libprotobuf-dev
      - libprotobuf-lite8
      - libprotobuf8
      - libprotoc-dev
      - libtbb-dev
      - libtbb2
      - libtool
      - libuuid1
      - libx11-dev
      - libxi-dev
      - libxmu-dev
      - libzmq3-dev
      - mercurial
      - meshlab
      - nvidia-profiler
      - nvidia-visual-profiler
      - protobuf-compiler
      - subversion
      - uuid-dev
      - valgrind
      - xvfb

#repositories
  - name: clone meshify-superbuild
    git: repo=git@bitbucket.org:replicalabs/meshify-superbuild.git dest={{ ansible_env.HOME }}/meshify-superbuild accept_hostkey=yes

  - name: clone ceres-solver
    git: repo=https://ceres-solver.googlesource.com/ceres-solver dest={{ ansible_env.HOME }}/ceres-solver

  - name: configure ceres-solver
    sudo: true
    command: cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS:BOOL=ON
    args:
      chdir: '{{ ansible_env.HOME }}/ceres-solver/'
      creates: '{{ ansible_env.HOME }}/ceres-solver/cmake_install.cmake'

  - name: build & install ceres-solver
    sudo: true
    command: sudo make -j4 install
    args:
      chdir: '{{ ansible_env.HOME }}/ceres-solver/'
      creates: '/usr/local/include/ceres/ceres.h'
